/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  outputFileTracingIncludes: { '/[[...slug]]': ['./legacy-pages/**/*'] },
  devIndicators: false,
  async headers() {
    return [{
      source: '/:path*',
      headers: [
        { key: 'X-Content-Type-Options', value: 'nosniff' },
        { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' }
      ]
    }];
  },
  async redirects() {
    return [
      { source: '/blog-post-1', destination: '/blog/gmit-students-practical-training-junior-site-engineers', permanent: true },
      { source: '/blog-post-2', destination: '/blog/campus-recruitment-internship-program-gmit-davangere', permanent: true },
      { source: '/blog-post-3', destination: '/blog/aaraa-infrastructure-180mwp-leap-green-project-thoothukudi', permanent: true },
      { source: '/blog-post-4', destination: '/blog/solar-epc-civil-infrastructure-kudligi-karnataka', permanent: true },
      { source: '/blog-post-5', destination: '/blog/reliance-civil-interior-mep-fitout-chennai', permanent: true },
      { source: '/blog-post-6', destination: '/blog/institutional-development-vibgyor-group-hinjewadi', permanent: true },
      { source: '/blog-post-7', destination: '/blog/institutional-development-precast-works-srm-university-andhra-pradesh', permanent: true },
      { source: '/blog-post-8', destination: '/blog/engineering-site-construction-internship-training-programme', permanent: true },
      { source: '/blog-post-9', destination: '/blog/official-boat-apprenticeship-partnership-civil-engineering', permanent: true },
      { source: '/blog-post-10', destination: '/blog/140-6-mw-wind-solar-hybrid-project-karnataka', permanent: true },
      { source: '/onam-celebration-at-our-office', destination: '/blog/onam-celebration-at-our-office', permanent: true },
      { source: '/potluck-celebration-2026', destination: '/blog/potluck-celebration-2026', permanent: true },
      { source: '/140-6-mw-wind-solar-hybrid-power-project', destination: '/blog/140-6-mw-wind-solar-hybrid-project-karnataka', permanent: true },
      { source: '/reliance-civil-interior-mep-fitout', destination: '/blog/reliance-civil-interior-mep-fitout-chennai', permanent: true },
      { source: '/blog/reliance-civil-interior-mep-fitout', destination: '/blog/reliance-civil-interior-mep-fitout-chennai', permanent: true },
      { source: '/projects-details.html', destination: '/completed-projects', permanent: true },
      { source: '/icr-civil-foundation-solar-project-toravi-karnataka', destination: '/blog/icr-civil-foundation-solar-project-toravi-karnataka', permanent: true },
      { source: '/icr-civil-foundation-solar-project-toravi-karnataka.html', destination: '/blog/icr-civil-foundation-solar-project-toravi-karnataka', permanent: true },
      { source: '/blog/icr-civil-foundation-solar-project-toravi-karnataka.html', destination: '/blog/icr-civil-foundation-solar-project-toravi-karnataka', permanent: true },
      { source: '/projects-details', destination: '/completed-projects', permanent: true },
      { source: '/ongoingorchid-project.html', destination: '/project-details-orchid', permanent: true },
      { source: '/ongoingorchid-project', destination: '/project-details-orchid', permanent: true },
      { source: '/blog/rmky-industrial-construction-dobbaspet-karnataka', destination: '/blog/ramky-industrial-construction-dobbaspet-karnataka', permanent: true },
      { source: '/blog/rmky-industrial-construction-dobbaspet-karnataka.html', destination: '/blog/ramky-industrial-construction-dobbaspet-karnataka', permanent: true },
      { source: '/rmky-industrial-construction-dobbaspet-karnataka', destination: '/blog/ramky-industrial-construction-dobbaspet-karnataka', permanent: true },
      { source: '/rmky-industrial-construction-dobbaspet-karnataka.html', destination: '/blog/ramky-industrial-construction-dobbaspet-karnataka', permanent: true },
      { source: '/ramky-industrial-construction-dobbaspet-karnataka', destination: '/blog/ramky-industrial-construction-dobbaspet-karnataka', permanent: true },
      { source: '/ramky-industrial-construction-dobbaspet-karnataka.html', destination: '/blog/ramky-industrial-construction-dobbaspet-karnataka', permanent: true },
      { source: '/Institutional-Development-VIBGYOR-Group-Hinjewadi-Pune.html', destination: '/blog/institutional-development-vibgyor-group-hinjewadi', permanent: true },
      { source: '/institutional-development-vibgyor-group-hinjewadi.html', destination: '/blog/institutional-development-vibgyor-group-hinjewadi', permanent: true },
      { source: '/contact.html', destination: '/contact-us', permanent: true },
      { source: '/contact', destination: '/contact-us', permanent: true },
      { source: '/privacy-policy', destination: '/aaraa-privacy-policy', permanent: true },
      { source: '/about-us.html', destination: '/about', permanent: true },
      { source: '/about-us', destination: '/about', permanent: true },
      { source: '/our-services.html', destination: '/services', permanent: true },
      { source: '/our-services', destination: '/services', permanent: true },
      { source: '/careers.html', destination: '/careers', permanent: true },
      { source: '/leadership.html', destination: '/about', permanent: true },
      { source: '/leadership-details.html', destination: '/about', permanent: true },
      { source: '/epc-contractor-chennai', destination: '/construction/epc-contractor-chennai', permanent: true },
      { source: '/peb-company-chennai', destination: '/construction/peb-company-chennai', permanent: true },
      { source: '/solar-epc-company-chennai', destination: '/construction/solar-epc-company-chennai', permanent: true },
      { source: '/mep-contractor-chennai', destination: '/construction/mep-contractor-chennai', permanent: true },
      { source: '/steel-structure-contractor-chennai', destination: '/construction/steel-structure-contractor-chennai', permanent: true },
      { source: '/warehouse-construction-chennai', destination: '/construction/warehouse-construction-chennai', permanent: true },
      { source: '/industrial-construction-chennai', destination: '/construction/industrial-construction-chennai', permanent: true },
      { source: '/institutional-construction-chennai', destination: '/construction/institutional-construction-chennai', permanent: true },
      { source: '/infrastructure-construction-chennai', destination: '/construction/infrastructure-construction-chennai', permanent: true },
      { source: '/interior-fit-out-contractor-chennai', destination: '/construction/interior-fit-out-contractor-chennai', permanent: true },
      { source: '/renovation-contractor-chennai', destination: '/construction/renovation-contractor-chennai', permanent: true },
      { source: '/commercial-construction-chennai', destination: '/construction/commercial-construction-chennai', permanent: true },
      { source: '/renewable-energy-contractor-chennai', destination: '/construction/renewable-energy-contractor-chennai', permanent: true },
      { source: '/home-2.html', destination: '/', permanent: true },
      { source: '/home-3.html', destination: '/', permanent: true },
      { source: '/home-4.html', destination: '/', permanent: true },
      { source: '/home-5.html', destination: '/', permanent: true },
      { source: '/why-choose-us.html', destination: '/about', permanent: true },
      { source: '/core-values.html', destination: '/about', permanent: true },
      { source: '/what-we-do.html', destination: '/services', permanent: true },
      { source: '/what-we-do-detail.html', destination: '/services', permanent: true },
      { source: '/working-process.html', destination: '/about', permanent: true },
      { source: '/testimonials.html', destination: '/about', permanent: true },
      { source: '/pricing.html', destination: '/contact-us', permanent: true },
      { source: '/shop.html', destination: '/', permanent: true },
      { source: '/shop-detail.html', destination: '/', permanent: true },
      { source: '/index.html', destination: '/', permanent: true },
      { source: '/:path*.html', destination: '/:path*', permanent: true }
    ];
  }
};

export default nextConfig;
